"""Orderfield kernel internals — field, spec, pack, regime, cli.

Public CLI entry remains `scripts/of.py`. Tests import this package as `of`.
Barrel: the imports below are the re-export list (`of.X`, the names tests
use); no `__all__`. Anything else imports from its module (`of.field`, ...).
"""
from __future__ import annotations

import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from of_adapters import (  # noqa: F401
    ADAPTER_BINS,
    ADAPTER_ORDER,
    INLINE_CONTRACT_ADAPTERS,
    AdapterBalance,
    AdapterDetect,
    AdapterHints,
    AdapterResume,
    AgyDeniedActions,
    SpawnAdapterMissing,
    OutputSchema,
    StreamJson,
    build_spawn_argv,
    missing_tools,
    pick_adapter,
)

from of.host_ram import AgentBand, HostRam  # noqa: F401

from of.field import (  # noqa: F401
    CHECKPOINT_MAX_CHARS,
    CHECKPOINT_MAX_LINES,
    LEARNING_MAX_CHARS,
    LEARNING_MAX_LINES,
    LearningLint,
    FIELD_SLAVE_MD,
    MUTATING_COMMANDS,
    MUTATING_COMMANDS_ORDER,
    mutating_commands_prose,
    PROTOCOL_SLAVE_MD,
    PROTOCOL_WRITABLE_KEY,
    PUBLIC_SCHEMA_FILES,
    PULSE_QUIET_SECONDS,
    PULSE_STALE_MINUTES,
    REDACTED,
    RETENTION_SECONDS,
    ROLE_CONTRACTS,
    apply_field_retention,
    ArgvRedact,
    argv_preview,
    artifact_generation,
    default_order,
    default_state,
    default_worktree_path,
    dump_json,
    field_lock,
    ActiveField,
    AuditPressure,
    ClosedScratch,
    DoctorSkew,
    FieldRoster,
    PackRoster,
    RootStub,
    FieldSignal,
    OrphanPacked,
    PackedAge,
    SpawnRecord,
    SkillVersionSkew,
    UpdateAsk,
    find_root,
    installed_version,
    load_json,
    load_order,
    load_state,
    load_wave_report,
    maybe_notify_update,
    child_pulse_verdict,
    CollectReady,
    DeadStartedOnly,
    EscalateUnblock,
    LiveQuietStuck,
    next_legal_action,
    open_backlog,
    parse_utc,
    proc_pcpu,
    pulse_verdict,
    redact_text,
    repo_newest_mtime,
    require_nonsymlink_kernel_root,
    require_public_schema,
    save_order,
    save_state,
    save_worktrees,
    semver_tuple,
    session_path,
    sha256_text,
    utc_now,
    schema_unknown_keywords,
    validate_order,
    validate_schema,
    validate_state,
    validate_wave_report,
    wave_dir,
    write_phase_md,
)

from of.spec import (  # noqa: F401
    ContractSurface,
    WebhookPair,
    REQ_ID_RE,
    apply_requirement_patches,
    classify_requirement_prefix,
    extract_requirements_from_spec,
    looks_like_deictic_brief,
    merge_extracted_requirements,
    requirement_counts,
    requirement_coverage_errors,
    requirement_is_pair,
    requirement_surface,
    spec_bytes_hash,
    SpecDiff,
    spec_diff_lines,
)

from of.receipt import EvidenceReceipt  # noqa: F401

from of.pack import (  # noqa: F401
    PACKET_IDENTITY_FIELDS,
    SLICE_WARN_CHARS,
    OwnsPathCoverage,
    ReviewScope,
    SharedWorktree,
    SliceLint,
    completed_children,
    in_flight_children,
    owns_paths_overlap,
    packet_digest,
    order_bind_digest,
    packet_is_stale,
    PacketRevStale,
    CloseEvidence,
    CodexNullOmit,
    OwnedWrite,
    ResidualQuality,
    render_prompt,
    slave_md,
    slave_md_path,
    validate_packet,
    validate_residual,
)

from of.regime import (  # noqa: F401
    DoneWhenLint,
    PlanCoverage,
    PlanDocSync,
    PlanIngress,
    PlanWriteBack,
    RunbookPath,
    REGIMES,
    RESERVED_REGIMES,
    RUNTIME_ENFORCED,
    RUNTIME_OWNERSHIP,
    UNCERTAINTY_SCALE_OUT_FLOOR,
    _select_regime,
    apply_patches,
    closed_phases,
    decide_regime,
    HostWriteDenial,
    done_when_closed,
    hold_if_partial_in_flight,
    landed_complete_in_flight_reason,
    done_when_for,
    done_when_tag,
    mark_done_when_closed,
    mission_done_when,
    IntegrationDigest,
    phase_done_when,
    phase_transition_errors,
    wave_report_covers_packets,
)

from of.cli import (  # noqa: F401
    EVAL_UNITTEST_MODULES,
    CloseChecklist,
    CloseProof,
    ContrastDiff,
    ContrastReport,
    EvaluatorPacket,
    EfficiencySignal,
    HandoffReport,
    DriveAfterIntegrate,
    ObservationPack,
    InFlightSignal,
    PulseProgress,
    StatusReport,
    eval_pack_child,
    eval_setup_recovery_active_field_pointer,
    eval_setup_recovery_contrast_close_contract,
    eval_setup_recovery_mission_rewrite,
    eval_setup_recovery_midflight_amend,
    MidFlightAmendEval,
    eval_setup_recovery_multi_wave_residual,
    MultiWaveResidualEval,
    eval_setup_recovery_multi_wave_close_checklist,
    eval_setup_recovery_threshold_stop_spawn,
    ThresholdStopSpawnEval,
    ProcessDeathResume,
    WaveReportQualityEval,
    eval_setup_recovery_packed_age,
    eval_setup_recovery_doctor_one_pass,
    eval_setup_recovery_doctor_closed_historical,
    eval_setup_recovery_plan_doc_sync,
    eval_setup_recovery_plan_first_coverage,
    ObservationPackEval,
    PlanDocSyncEval,
    PlanCoverageEval,
    PlanIngressEval,
    eval_write_done_residual,
    pulse_once,
    resume_next_lines,
)
